### ISSUE TITLE
Secure websockets on self-signed certificates

### ISSUE THREAD

**Issue by fwsGonzo** [Fitblip/wsstat#5]
It does seem like self-signed certificates can't be tested because wsstat can't automatically accept unverifiable certificates. Is this something that an option can be added for?

**Comment by fwsGonzo** [comment]
I can solve this problem on my end with:
change line 9 to just `import ssl` and

line 137: `websocket = yield from websockets.connect(**connection_args, ssl=ssl._create_unverified_context())`

**Comment by Fitblip** [comment]
Hey @fwsGonzo - sorry for the delay! I can add that as an option for sure, I'm just really busy with work stuff right now so it might take a bit.

Cheers!

**Comment by abawchen** [comment]
@Fitblip 
If it is okay, I can take care this issue by adding `-s --self-signed-cert` as the args.
